format shell scripts

diff --git a/bin/configure-gcloud-environment b/bin/configure-gcloud-environment
--- a/bin/configure-gcloud-environment
+++ b/bin/configure-gcloud-environment
@@ -1,21 +1,21 @@
 #!/bin/bash
-GCLOUD=$(command -v gcloud);
+GCLOUD=$(command -v gcloud)
 if [ -z "${GCLOUD}" ]; then
-  echo "Unable to find binary for gcloud.";
-  exit 1;
-fi;
+  echo "Unable to find binary for gcloud."
+  exit 1
+fi
 
 if [ -z "${GCLOUD_PROJECT_ID}" ]; then
-  echo "No project id is available for gcloud configuration, ensure that \$GCLOUD_PROJECT_ID is set for project.";
-  exit 1;
-fi;
+  echo "No project id is available for gcloud configuration, ensure that \$GCLOUD_PROJECT_ID is set for project."
+  exit 1
+fi
 
 if [ -z "${GCLOUD_SERVICE_ACCOUNT}" ]; then
-  echo "No service account configuration is available for gcloud, ensure that \$GCLOUD_SERVICE_ACCOUNT is set for project.";
-  exit 1;
-fi;
+  echo "No service account configuration is available for gcloud, ensure that \$GCLOUD_SERVICE_ACCOUNT is set for project."
+  exit 1
+fi
 
-$GCLOUD config set project "${GCLOUD_PROJECT_ID}";
+$GCLOUD config set project "${GCLOUD_PROJECT_ID}"
 
-echo "${GCLOUD_SERVICE_ACCOUNT}" > service-account.json;
-$GCLOUD auth activate-service-account --key-file service-account.json;
+echo "${GCLOUD_SERVICE_ACCOUNT}" >service-account.json
+$GCLOUD auth activate-service-account --key-file service-account.json
diff --git a/bin/run-integration-test b/bin/run-integration-test
--- a/bin/run-integration-test
+++ b/bin/run-integration-test
@@ -1,19 +1,19 @@
 #!/bin/bash
-PROJECT_DIRECTORY="$(dirname "${0}")/..";
-APK_DIRECTORY="${PROJECT_DIRECTORY}/app/build/outputs/apk";
-RELEASE_APK="${APK_DIRECTORY}/release/app-release.apk";
-RELEASE_TEST_APK="${APK_DIRECTORY}/androidTest/release/app-release-androidTest.apk";
+PROJECT_DIRECTORY="$(dirname "${0}")/.."
+APK_DIRECTORY="${PROJECT_DIRECTORY}/app/build/outputs/apk"
+RELEASE_APK="${APK_DIRECTORY}/release/app-release.apk"
+RELEASE_TEST_APK="${APK_DIRECTORY}/androidTest/release/app-release-androidTest.apk"
 
-GCLOUD=$(command -v gcloud);
+GCLOUD=$(command -v gcloud)
 if [ -z "${GCLOUD}" ]; then
-  echo "Unable to find binary for gcloud.";
-  exit 1;
-fi;
+  echo "Unable to find binary for gcloud."
+  exit 1
+fi
 
 $GCLOUD firebase test android run \
   --type instrumentation \
   --app "${RELEASE_APK}" \
   --test "${RELEASE_TEST_APK}" \
   --device model=Pixel2,version=28,locale=en,orientation=portrait \
-  --timeout 90s;
-exit $?;
+  --timeout 90s
+exit $?
diff --git a/bin/tag b/bin/tag
--- a/bin/tag
+++ b/bin/tag
@@ -1,13 +1,13 @@
 #!/bin/bash
-TAG=$1;
+TAG=$1
 if [ -z "${TAG}" ]; then
-  echo "No valid tag name have been supplied.";
-  echo "Usage: $0 0.9.15";
-  exit 1;
-fi;
+  echo "No valid tag name have been supplied."
+  echo "Usage: $0 0.9.15"
+  exit 1
+fi
 
 if ! git tag -a -m "Release v${TAG}" "${TAG}"; then
-  echo "Unable to create tag: ${TAG}";
-  exit 1;
-fi;
-exit $?;
+  echo "Unable to create tag: ${TAG}"
+  exit 1
+fi
+exit $?
