attempt to resolve issue with instrumentation tests failing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -169,8 +169,8 @@ app:instrumented test:
     - echo "${GCLOUD_SERVICE_ACCOUNT}" >service-account.json
     - gcloud auth activate-service-account --key-file service-account.json
   script: |
-    DEVICE="model=$DEVICE_MODEL,version=$DEVICE_API_VERSION,locale=$DEVICE_LOCALE,orientation=$DEVICE_ORIENTATION"
-    RESULTS_DIRECTORY="build-$CI_COMMIT_SHA"
+    DEVICE="model=$DEVICE_MODEL,version=$DEVICE_API_VERSION,locale=$DEVICE_LOCALE,orientation=$DEVICE_ORIENTATION";
+    RESULTS_DIRECTORY="build-$CI_COMMIT_SHA";
 
     LOG_FILE="instrumentation.log";
     gcloud firebase test android run \
@@ -181,32 +181,32 @@ app:instrumented test:
       --environment-variables coverage=true,coverageFile="/sdcard/coverage.ec" \
       --directories-to-pull /sdcard \
       --results-dir "$RESULTS_DIRECTORY" \
-      --timeout 90s 1>"$LOG_FILE" 2>&1
-    FIREBASE_EXIT_VALUE=$?
-    cat "$LOG_FILE"
+      --timeout 90s 1>"$LOG_FILE" 2>&1;
+    FIREBASE_EXIT_VALUE=$?;
+    cat "$LOG_FILE";
 
-    BUCKET_NAME=$(grep -oP "(?<=browser\/).*(?<=\/$RESULTS_DIRECTORY)" "$LOG_FILE")
+    BUCKET_NAME=$(grep -oP "(?<=browser\/).*(?<=\/$RESULTS_DIRECTORY)" "$LOG_FILE");
     if [ -z "$BUCKET_NAME" ]; then
-      echo "Unable to parse bucket name from log file."
-      exit 1
+      echo "Unable to parse bucket name from log file.";
+      exit 1;
     fi
 
-    BUCKET_DEVICE_FOLDER="$DEVICE_MODEL-$DEVICE_API_VERSION-$DEVICE_LOCALE-$DEVICE_ORIENTATION"
-    BUCKET_COVERAGE_PATH="gs://$BUCKET_NAME/$BUCKET_DEVICE_FOLDER/artifacts/coverage.ec"
-    BUCKET_REPORT_PATH="gs://$BUCKET_NAME/$BUCKET_DEVICE_FOLDER/*.xml"
+    BUCKET_DEVICE_FOLDER="$DEVICE_MODEL-$DEVICE_API_VERSION-$DEVICE_LOCALE-$DEVICE_ORIENTATION";
+    BUCKET_COVERAGE_PATH="gs://$BUCKET_NAME/$BUCKET_DEVICE_FOLDER/artifacts/coverage.ec";
+    BUCKET_REPORT_PATH="gs://$BUCKET_NAME/$BUCKET_DEVICE_FOLDER/*.xml";
 
     mkdir -p "$COVERAGE_OUTPUT_DIRECTORY";
     if ! gsutil -m cp -R "$BUCKET_COVERAGE_PATH" "$COVERAGE_OUTPUT_DIRECTORY"; then
-      echo "Unable to pull down coverage output from bucket."
-      exit $?
+      echo "Unable to pull down coverage output from bucket.";
+      exit $?;
     fi
 
     mkdir -p "$REPORT_OUTPUT_DIRECTORY";
     if ! gsutil -m cp -R "$BUCKET_REPORT_PATH" "$REPORT_OUTPUT_DIRECTORY"; then
-      echo "Unable to pull down report output from bucket."
-      exit $?
+      echo "Unable to pull down report output from bucket.";
+      exit $?;
     fi
-    exit $FIREBASE_EXIT_VALUE
+    exit $FIREBASE_EXIT_VALUE;
   needs:
     - app:build
   artifacts:
